// Jiang Bian. Copyright (C) 2013. MIT License.
#ifndef __TED_CONFIG_H__
#define __TED_CONFIG_H__

#include <boost/preprocessor/stringize.hpp>

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "config.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */

/* #undef USE_STD_CXX_11 */

#if !defined(ARMA_USE_CXX11)
#define ARMA_USE_CXX11
//// Uncomment the above line if you have a C++ compiler that supports the C++11 standard
//// This will enable additional features, such as use of initialiser lists
#endif



#endif
